changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - "dependabot[bot]"
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - maintenance
        - chore
    - title: Other changes
      labels:
        - "*"
