export const AI_SCULPTURE_EXAMPLES = [
  {
    slug: "tiny-cottage",
    prompt: "A tiny cottage with a pitched roof, chimney, door and two windows",
    recipe: {
      mode: "sculpture",
      name: "Tiny Hearth Cottage",
      subtitle: "A sturdy storybook house with a warm roof and bright windows",
      templateId: "gift-box",
      topperHeight: 38,
      topperWidth: 36,
      primaryColor: "#d7794f",
      secondaryColor: "#486b4a",
      detailColor: "#f3d88f",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "The cottage uses a broad fused body, pitched roof and raised facade details.",
      program: {
        version: 1,
        nodes: [
          { id: "house", kind: "rounded-box", operation: "add", attachTo: "core", position: [0, 0.3, 0], size: [0.72, 0.44, 0.62], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 10 },
          { id: "roof", kind: "roof", operation: "add", attachTo: "house", position: [0, 0.59, 0], size: [0.9, 0.34, 0.72], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 8 },
          { id: "door", kind: "rounded-box", operation: "add", attachTo: "house", position: [0, 0.24, 0.32], size: [0.2, 0.28, 0.08], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 8 },
          { id: "window", kind: "rounded-box", operation: "add", attachTo: "house", position: [0.23, 0.39, 0.33], size: [0.14, 0.14, 0.07], rotation: [0, 0, 0], color: "detail", symmetry: "mirror-x", segments: 8 },
          { id: "chimney", kind: "cylinder", operation: "add", attachTo: "roof", position: [0.16, 0.62, -0.12], size: [0.13, 0.27, 0.13], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 8 },
        ],
      },
    },
  },
  {
    slug: "waving-astronaut",
    prompt: "A friendly astronaut waving with a round helmet and sturdy boots",
    recipe: {
      mode: "sculpture",
      name: "Orbit Buddy",
      subtitle: "A waving astronaut with a broad suit, visor and planted boots",
      templateId: "santa",
      topperHeight: 44,
      topperWidth: 34,
      primaryColor: "#e9ece8",
      secondaryColor: "#4a7f91",
      detailColor: "#ef9b45",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "Large suit masses and fused limbs keep the character readable and sturdy.",
      program: {
        version: 1,
        nodes: [
          { id: "torso", kind: "capsule", operation: "add", attachTo: "core", position: [0, 0.43, 0], size: [0.38, 0.43, 0.3], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 14 },
          { id: "helmet", kind: "ellipsoid", operation: "add", attachTo: "torso", position: [0, 0.72, 0], size: [0.46, 0.34, 0.38], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 16 },
          { id: "visor", kind: "ellipsoid", operation: "add", attachTo: "helmet", position: [0, 0.73, 0.18], size: [0.33, 0.2, 0.08], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 16 },
          { id: "left-arm", kind: "capsule", operation: "add", attachTo: "torso", position: [-0.27, 0.48, 0], size: [0.14, 0.38, 0.15], rotation: [0, 0, -34], color: "primary", symmetry: "none", segments: 12 },
          { id: "wave-arm", kind: "capsule", operation: "add", attachTo: "torso", position: [0.28, 0.58, 0], size: [0.14, 0.42, 0.15], rotation: [0, 0, 32], color: "primary", symmetry: "none", segments: 12 },
          { id: "glove", kind: "ellipsoid", operation: "add", attachTo: "wave-arm", position: [0.39, 0.77, 0], size: [0.16, 0.15, 0.17], rotation: [0, 0, 0], color: "detail", symmetry: "none", segments: 12 },
          { id: "leg", kind: "capsule", operation: "add", attachTo: "torso", position: [0.12, 0.18, 0], size: [0.15, 0.32, 0.18], rotation: [0, 0, -5], color: "primary", symmetry: "mirror-x", segments: 12 },
          { id: "boot", kind: "rounded-box", operation: "add", attachTo: "leg", position: [0.14, 0.07, 0.06], size: [0.21, 0.13, 0.26], rotation: [0, 0, 0], color: "detail", symmetry: "mirror-x", segments: 8 },
          { id: "chest-badge", kind: "star", operation: "add", attachTo: "torso", position: [0, 0.47, 0.17], size: [0.15, 0.14, 0.07], rotation: [0, 0, 0], color: "detail", symmetry: "none", segments: 5 },
        ],
      },
    },
  },
  {
    slug: "dragon-fruit",
    prompt: "A dragon fruit with layered leafy scales and a short stem",
    recipe: {
      mode: "sculpture",
      name: "Dragon Fruit Bloom",
      subtitle: "A plump tropical fruit wrapped in layered green fins",
      templateId: "strawberry",
      topperHeight: 39,
      topperWidth: 32,
      primaryColor: "#c83f70",
      secondaryColor: "#5a8a4b",
      detailColor: "#f0d7df",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "A large central fruit carries thick mirrored leaf fins instead of fragile scales.",
      program: {
        version: 1,
        nodes: [
          { id: "fruit", kind: "ellipsoid", operation: "add", attachTo: "core", position: [0, 0.45, 0], size: [0.66, 0.7, 0.62], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 16 },
          { id: "top-leaf", kind: "leaf", operation: "add", attachTo: "fruit", position: [0, 0.8, 0], size: [0.23, 0.3, 0.12], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 12 },
          { id: "upper-fin", kind: "leaf", operation: "add", attachTo: "fruit", position: [0.2, 0.65, 0.16], size: [0.22, 0.28, 0.12], rotation: [-18, 20, -35], color: "secondary", symmetry: "mirror-x", segments: 12 },
          { id: "mid-fin", kind: "leaf", operation: "add", attachTo: "fruit", position: [0.28, 0.46, -0.08], size: [0.23, 0.3, 0.12], rotation: [10, -15, -68], color: "secondary", symmetry: "mirror-x", segments: 12 },
          { id: "front-fin", kind: "leaf", operation: "add", attachTo: "fruit", position: [0, 0.4, 0.29], size: [0.21, 0.25, 0.1], rotation: [18, 0, 0], color: "secondary", symmetry: "none", segments: 12 },
          { id: "lower-fin", kind: "leaf", operation: "add", attachTo: "fruit", position: [0.19, 0.25, 0.15], size: [0.2, 0.25, 0.11], rotation: [-20, 16, -120], color: "secondary", symmetry: "mirror-x", segments: 12 },
          { id: "stem", kind: "cylinder", operation: "add", attachTo: "top-leaf", position: [0, 0.91, 0], size: [0.12, 0.16, 0.12], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 9 },
        ],
      },
    },
  },
  {
    slug: "pomegranate-slice",
    prompt: "A sliced pomegranate with a round shell, visible chunky seed clusters, and a leafy crown",
    recipe: {
      mode: "sculpture",
      name: "Pomegranate Jewel",
      subtitle: "An open ruby fruit with a clear seeded face and leafy crown",
      templateId: "lemon",
      topperHeight: 38,
      topperWidth: 34,
      primaryColor: "#b92f46",
      secondaryColor: "#e86472",
      detailColor: "#f3c1b8",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "Layered front-facing discs and radial seed rings make the cut face readable without fragile loose pieces.",
      program: {
        version: 1,
        nodes: [
          { id: "rind", kind: "disc", operation: "add", attachTo: "core", position: [0, 0.47, 0], size: [0.72, 0.72, 0.28], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 16 },
          { id: "flesh", kind: "disc", operation: "add", attachTo: "rind", position: [0, 0.47, 0.11], size: [0.6, 0.6, 0.18], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 16 },
          { id: "outer-seed", kind: "disc", operation: "add", attachTo: "flesh", position: [0.19, 0.47, 0.18], size: [0.12, 0.15, 0.12], rotation: [0, 0, 0], color: "detail", symmetry: "radial-6-z", segments: 10 },
          { id: "inner-seed", kind: "disc", operation: "add", attachTo: "flesh", position: [0.09, 0.47, 0.185], size: [0.1, 0.12, 0.1], rotation: [0, 0, 0], color: "detail", symmetry: "radial-5-z", segments: 10 },
          { id: "crown-center", kind: "leaf", operation: "add", attachTo: "rind", position: [0, 0.82, 0], size: [0.19, 0.25, 0.12], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 9 },
        ],
      },
    },
  },
  {
    slug: "octopus",
    prompt: "A cheerful octopus with eight chunky curling arms and big eyes",
    recipe: {
      mode: "sculpture",
      name: "Cheerful Octopus",
      subtitle: "A round sea friend with chunky radial arms and bright eyes",
      templateId: "frog",
      topperHeight: 34,
      topperWidth: 38,
      primaryColor: "#8b5ea8",
      secondaryColor: "#d681ad",
      detailColor: "#f4eee2",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "The tentacles are short fused capsules arranged around a broad central body.",
      program: {
        version: 1,
        nodes: [
          { id: "body", kind: "ellipsoid", operation: "add", attachTo: "core", position: [0, 0.55, 0], size: [0.58, 0.52, 0.56], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 15 },
          { id: "front-arm", kind: "capsule", operation: "add", attachTo: "body", position: [0.15, 0.23, 0.24], size: [0.14, 0.42, 0.16], rotation: [32, 0, -24], color: "secondary", symmetry: "mirror-x", segments: 11 },
          { id: "side-arm", kind: "capsule", operation: "add", attachTo: "body", position: [0.31, 0.24, 0], size: [0.15, 0.43, 0.16], rotation: [0, 0, -55], color: "primary", symmetry: "mirror-x", segments: 11 },
          { id: "back-arm", kind: "capsule", operation: "add", attachTo: "body", position: [0.15, 0.23, -0.23], size: [0.14, 0.42, 0.16], rotation: [-32, 0, -24], color: "secondary", symmetry: "mirror-x", segments: 11 },
          { id: "center-arm", kind: "capsule", operation: "add", attachTo: "body", position: [0, 0.2, 0.3], size: [0.15, 0.38, 0.17], rotation: [45, 0, 0], color: "primary", symmetry: "mirror-z", segments: 11 },
          { id: "eye", kind: "ellipsoid", operation: "add", attachTo: "body", position: [0.13, 0.6, 0.27], size: [0.14, 0.16, 0.08], rotation: [0, 0, 0], color: "detail", symmetry: "mirror-x", segments: 12 },
        ],
      },
    },
  },
  {
    slug: "garden-rocket",
    prompt: "A retro rocket with a round window, nose cone and three sturdy fins",
    recipe: {
      mode: "sculpture",
      name: "Garden Rocket",
      subtitle: "A compact retro rocket with a porthole and broad fins",
      templateId: "bamboo",
      topperHeight: 46,
      topperWidth: 30,
      primaryColor: "#e7e4d9",
      secondaryColor: "#ca5348",
      detailColor: "#4d7d89",
      accentColor: "#d7d0bf",
      faceted: false,
      shape: {},
      creativeNote: "A thick central fuselage and oversized fused fins make the rocket printable.",
      program: {
        version: 1,
        nodes: [
          { id: "fuselage", kind: "cylinder", operation: "add", attachTo: "core", position: [0, 0.48, 0], size: [0.42, 0.62, 0.42], rotation: [0, 0, 0], color: "primary", symmetry: "none", segments: 14 },
          { id: "nose", kind: "cone", operation: "add", attachTo: "fuselage", position: [0, 0.83, 0], size: [0.44, 0.28, 0.44], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 14 },
          { id: "window", kind: "torus", operation: "add", attachTo: "fuselage", position: [0, 0.58, 0.22], size: [0.26, 0.26, 0.09], rotation: [0, 0, 0], color: "detail", symmetry: "none", segments: 12 },
          { id: "fin", kind: "leaf", operation: "add", attachTo: "fuselage", position: [0.24, 0.26, 0], size: [0.22, 0.34, 0.14], rotation: [0, 0, -24], color: "secondary", symmetry: "mirror-x", segments: 9 },
          { id: "front-fin", kind: "leaf", operation: "add", attachTo: "fuselage", position: [0, 0.25, 0.2], size: [0.14, 0.33, 0.22], rotation: [0, 0, 0], color: "secondary", symmetry: "none", segments: 9 },
          { id: "flame", kind: "cone", operation: "add", attachTo: "fuselage", position: [0, 0.1, 0], size: [0.25, 0.25, 0.25], rotation: [180, 0, 0], color: "detail", symmetry: "none", segments: 10 },
        ],
      },
    },
  },
] as const;
